pls work

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -15,6 +15,16 @@ variables:
   export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/gitlab_oidc_token
   export AWS_ROLE_ARN="$AWS_ROLE_ARN"
   export AWS_REGION="$AWS_REGION"
+
+.ssh_setup: &ssh_setup
+  - apk add --no-cache openssh-client
+  - mkdir -p ~/.ssh
+  - test -n "$SSH_PRIVATE_KEY" || (echo "SSH_PRIVATE_KEY env var is empty" && exit 1)
+  - test -s "$SSH_PRIVATE_KEY" || (echo "SSH_PRIVATE_KEY file missing/empty at: $SSH_PRIVATE_KEY" && exit 1)
+  - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
+  - chmod 600 ~/.ssh/id_rsa
+  - ssh-keygen -y -f ~/.ssh/id_rsa >/dev/null
+  - test -n "$EC2_PUBLIC_IP" || (echo "EC2_PUBLIC_IP is empty (dotenv from apply_infra missing?)" && exit 1)
   
 
 default:
@@ -85,20 +95,8 @@ apply_infra:
   artifacts:
     reports:
       dotenv: deploy.env
-  artifacts:
-    reports:
-      dotenv: deploy.env
 
-.infra_job:
-  image: alpine:3.19
-  before_script:
-    - apk add --no-cache openssh-client
-    - mkdir -p ~/.ssh
-    - test -n "$SSH_PRIVATE_KEY" || (echo "SSH_PRIVATE_KEY env var is empty" && exit 1)
-    - test -s "$SSH_PRIVATE_KEY" || (echo "SSH_PRIVATE_KEY file missing/empty at: $SSH_PRIVATE_KEY" && exit 1)
-    - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
-    - chmod 600 ~/.ssh/id_rsa
-    - ssh-keygen -y -f ~/.ssh/id_rsa >/dev/null
+
   
 
 configure_networking:
@@ -108,14 +106,7 @@ configure_networking:
       artifacts: true
   image: alpine:3.19
   script:
-    - apk add --no-cache openssh-client
-    - mkdir -p ~/.ssh
-    - echo "SSH_PRIVATE_KEY path '$SSH_PRIVATE_KEY'"
-    - ls -la "$SSH_PRIVATE_KEY" || true
-    - wc -c "$SSH_PRIVATE_KEY" || true
-    - head -n 1 "$SSH_PRIVATE_KEY" || true
-    - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
-    - chmod 600 ~/.ssh/id_rsa
+    - *ssh_setup
     - |
       ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
         echo "Waiting for EC2 boot script (cloud-init) to finish..."
@@ -135,10 +126,11 @@ configure_networking:
       EOF
 
 deploy_pods:
-  extends: .infra_job
   stage: k8s_deploy
+  image: alpine:3.19
   needs: [apply_infra, configure_networking]
   script:
+    - *ssh_setup
     - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP "sudo chown -R ubuntu:ubuntu /home/ubuntu/k8s"
     - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r k8s/ ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/
     - |
@@ -149,12 +141,13 @@ deploy_pods:
 
 observe_cluster:
   stage: observe
-  extends: .infra_job
+  image: alpine:3.19
   needs:
     - job: apply_infra
       artifacts: true
     - job: deploy_pods
   script:
+    - *ssh_setup
     - |
       ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
         helm upgrade --install redis-exporter prometheus-community/prometheus-redis-exporter \
